# Generated by Django 6.0 on 2026-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('BENEFICIARIO', 'Beneficiário'), ('CLIENTE', 'Cliente'), ('OUTRO', 'Outro')], max_length=20)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codor', models.CharField(blank=True, max_length=10, verbose_name='CodOrigem')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('LT', 'Litro'), ('MT', 'Metro'), ('CX', 'Caixa'), ('RL', 'Rolo'), ('BO', 'Bobina')], max_length=3, verbose_name='Unidade')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codor'],
                'unique_together': {('codor', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codsv', models.CharField(blank=True, max_length=10, null=True, verbose_name='CodSv')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('LT', 'Litro'), ('MT', 'Metro'), ('CX', 'Caixa'), ('RL', 'Rolo'), ('BO', 'Bobina')], max_length=3, verbose_name='Unidade')),
                ('preco_servico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['codsv'],
                'unique_together': {('codsv', 'descricao')},
            },
        ),
    ]
