# Generated by Django 6.0 on 2026-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'À Vista'), ('parcelado', 'Parcelado'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro')], default='avista', max_length=20, null=True),
        ),
    ]
