# Generated by Django 6.0 on 2026-02-24 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('comercial', '0002_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('custo_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cmv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.vendaitem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.venda')),
            ],
            options={
                'verbose_name': 'CMV do Item',
                'verbose_name_plural': 'CMV dos Itens',
                'ordering': ['data'],
            },
        ),
    ]
