# Generated by Django 6.0 on 2026-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_cmvitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Kilograma'), ('LT', 'Litro'), ('MT', 'Metro'), ('CX', 'Caixa'), ('RL', 'Rolo'), ('BO', 'Bobina')], default='UN', max_length=3, verbose_name='Unidade'),
        ),
    ]
