# Generated by Django 6.0 on 2026-02-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_financeiropagar_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeirolancamento',
            name='tipo',
        ),
    ]
