# Generated by Django 6.0 on 2026-02-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_financeirolancamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamovimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='financeiroreceber',
            name='caixa_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_receber', to='financeiro.caixamovimento'),
        ),
        migrations.AddField(
            model_name='financeiroreceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='financeiropagar',
            name='caixa_movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_pagar', to='financeiro.caixamovimento'),
        ),
        migrations.AlterField(
            model_name='financeiroreceber',
            name='origem',
            field=models.CharField(choices=[('LANCAMENTO', 'Lançamento'), ('MANUAL', 'Manual'), ('VENDA', 'Venda'), ('RECEITA', 'Receita Diversa')], max_length=20),
        ),
    ]
