# Generated by Django 6.0 on 2026-02-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_caixamovimento_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixamovimento',
            name='saldo_apos',
        ),
        migrations.RemoveField(
            model_name='caixamovimento',
            name='status',
        ),
        migrations.AddField(
            model_name='caixamovimento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caixamovimento',
            name='origem',
            field=models.CharField(choices=[('RECEITA', 'Recebimento de Título'), ('PAGAMENTO', 'Pagamento de Título'), ('MANUAL', 'Ajuste Manual'), ('COMPRA', 'Compra'), ('TRANSFERENCIA', 'Transferência')], max_length=20),
        ),
    ]
