# Generated by Django 6.0 on 2026-02-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_remove_caixamovimento_saldo_apos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiropagar',
            name='referencia_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.financeirolancamento'),
        ),
        migrations.AlterField(
            model_name='financeiroreceber',
            name='referencia_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.financeirolancamento'),
        ),
    ]
