# Generated by Django 6.0 on 2026-02-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_financeiropagar_referencia_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiropagar',
            old_name='referencia_id',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='financeiroreceber',
            old_name='referencia_id',
            new_name='referencia',
        ),
    ]
