# Generated by Django 6.0 on 2026-02-17 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financeiro', '0007_rename_referencia_id_financeiropagar_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiropagar',
            name='referencia',
        ),
        migrations.AddField(
            model_name='financeiropagar',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='financeiropagar',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
