# Generated by Django 6.0 on 2026-02-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamovimento',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.caixa'),
        ),
    ]
