# Generated by Django 6.0 on 2026-02-17 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_caixamovimento_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaAbertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operador', models.CharField(max_length=100)),
                ('aberto', models.BooleanField(default=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.caixa')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operador', models.CharField(max_length=100)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abertura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financeiro.caixaabertura')),
            ],
        ),
    ]
