# Generated by Django 6.0 on 2026-02-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_caixaabertura_caixafechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiropagar',
            name='tipo',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='financeiroreceber',
            name='tipo',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
