# Generated by Django 6.0 on 2026-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_remove_financeiroreceber_referencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixamovimento',
            options={'verbose_name': 'Movimento de Caixa', 'verbose_name_plural': 'Movimentos de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='financeirocategoria',
            options={'verbose_name': 'Categoria Financeira', 'verbose_name_plural': 'Categorias Financeiras'},
        ),
        migrations.AlterModelOptions(
            name='financeirolancamento',
            options={'verbose_name': 'Lançamento Financeiro', 'verbose_name_plural': 'Lançamentos Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='financeiroreceber',
            options={'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.AddField(
            model_name='financeirocategoria',
            name='grupo_dre',
            field=models.CharField(blank=True, choices=[('RECEITA_BRUTA', 'Receita Bruta'), ('IMPOSTOS', 'Impostos sobre Vendas'), ('DESPESA_VENDAS', 'Despesas com Vendas'), ('DESPESA_ADM', 'Despesas Administrativas'), ('DESPESA_GERAIS', 'Despesas Gerais'), ('OUTRAS_RECEITAS', 'Outras Receitas'), ('OUTRAS_DESPESAS', 'Outras Despesas')], help_text='Define onde esta categoria aparece no DRE', max_length=30, null=True),
        ),
    ]
