# Generated by Django 6.0 on 2026-03-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_alter_caixamovimento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamovimento',
            name='referencia_tipo',
            field=models.CharField(blank=True, choices=[('R', 'Receber'), ('D', 'Pagar')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='financeirocategoria',
            name='grupo_dre',
            field=models.CharField(blank=True, choices=[('RECEITA_BRUTA', 'Receita Bruta'), ('DESPESA_VENDAS', 'Despesas com Vendas'), ('DESPESA_ADM', 'Despesas Administrativas'), ('DESPESA_GERAIS', 'Despesas Gerais'), ('RECEITA_PATRIMONIAL', 'Receitas Patrimoniais'), ('RECEITAS_FINANCEIRAS', 'Receitas Financeiras'), ('DESPESAS_FINANCEIRAS', 'Despesas Financeiras'), ('ICMS', 'ICMS'), ('ISS', 'ISS'), ('PIS', 'PIS'), ('COFINS', 'COFINS'), ('IRPJ', 'IRPJ'), ('CSLL', 'CSLL')], help_text='Define onde esta categoria aparece no DRE', max_length=30, null=True, verbose_name='Grupo DRE'),
        ),
    ]
